{
 "title": "Truenas",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "hostname", "query": { "query": "truenas_uptime_uptime" } }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "truenas_uptime_uptime{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "truenas_aggregation_cpu_gauge_system{hostname=\"$hostname\", device=\"average\"} + truenas_aggregation_cpu_gauge_user{hostname=\"$hostname\", device=\"average\"} + truenas_aggregation_cpu_gauge_nice{hostname=\"$hostname\", device=\"average\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dataset Space Free",
   "type": "stat",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "truenas_dataset_df_complex_free{hostname=\"$hostname\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "truenas_disktemp_temperature{hostname=\"$hostname\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "RAM Free",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "truenas_memory_free{hostname=\"$hostname\"}",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "ARC Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "truenas_zfs_arc_cache_size_arc{hostname=\"$hostname\"}",
     "legendFormat": "ARC"
    },
    {
     "expr": "truenas_zfs_arc_cache_size_L2{hostname=\"$hostname\"}",
     "legendFormat": "L2"
    }
   ]
  },
  {
   "title": "ARC Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "truenas_zfs_arc_cache_ratio_arc{hostname=\"$hostname\"} * 100",
     "legendFormat": "ARC"
    },
    {
     "expr": "truenas_zfs_arc_cache_ratio_L2{hostname=\"$hostname\"} * 100",
     "legendFormat": "L2"
    }
   ]
  },
  {
   "title": "Interface Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "truenas_interface_packets_rx{hostname=\"$hostname\"}",
     "legendFormat": "{{device}} in"
    },
    {
     "expr": "truenas_interface_packets_tx{hostname=\"$hostname\"}",
     "legendFormat": "{{device}} out"
    }
   ]
  },
  {
   "title": "Disk I/O time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "truenas_disk_io_time_io_time{hostname=\"$hostname\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}